GETP-177 feat: 내 프로젝트 지원 목록 조회 기능 구현
Principes-Artis-Mechanicae/get-p-server pull request #117
Opened 2024-08-09 06:47 UTC by wlgns12370

## ✨ 구현한 기능
- 내 프로젝트 지원 목록 조회 기능

## 📢 논의하고 싶은 내용
- 해당 기능이 `ProjectApplicationDao`의 관심사로 가지게 하였는데, 다른 아이디어가 있는지 궁금합니다!

## 🎸 기타
- X

2024-08-13 12:35 UTC, scv1702 requested changes

2024-08-13 12:35 UTC, scv1702 commented on src/main/java/es/princip/getp/domain/project/query/dao/ProjectApplicationDao.java
> +    Page<AppliedProjectCardResponse> findPagedMyAppliedProjects(Pageable pageable, Long memberId, Boolean cancelled);
해당 메소드는 조회 대상이 프로젝트이기 때문에 `ProjectApplicationDao`와 적합하지 않아 보여요. 새로운 DAO 객체를 만들거나 `ProjectDao`로 옮기는 것은 어떨까요?

2024-08-13 12:35 UTC, scv1702 commented on src/main/java/es/princip/getp/domain/project/query/dao/ProjectApplicationQueryDslDao.java
위 의견의 근거로 조회 대상과 맞지 않은 DAO에 메소드를 구현하니 중복된 코드가 많이 발생하고 있어요.

2024-08-13 12:35 UTC, scv1702 commented on src/main/java/es/princip/getp/domain/project/query/presentation/AppliedProjectQueryController.java
> +    @GetMapping("/me/applications")
24-08-13 회의에서 얘기한대로 API 엔드 포인트를 조회하는 리소스와 맞게 `/people/me/projects`로 수정합시다!

2024-08-13 12:35 UTC, scv1702 commented on src/main/java/es/princip/getp/domain/project/query/dao/ProjectApplicationQueryDslDao.java
> +    private final ProjectApplicationDao projectApplicationDao;
해당 코드로 인해 의존성에 순환 관계가 발생하고 있어요. 또한 필요 없는 의존성이니 제거해주세요.

2024-08-13 12:35 UTC, scv1702 commented on src/test/java/es/princip/getp/domain/project/query/presentation/AppliedProjectQueryControllerTest.java
> +                                .attributes(key("default").value("false"))
쿼리 파라미터에 대한 설명도 Description 객체로 분리하면 어떨까요?

2024-08-19 02:46 UTC, wlgns12370 commented on src/test/java/es/princip/getp/domain/project/query/presentation/AppliedProjectQueryControllerTest.java
> +                                .attributes(key("default").value("false"))
`common.description.PaginationDescription.java` 파일을 만들어서 최대한 중복되는 코드를 합쳐봤습니다. 하지만 재사용을 고려해서 추가적인 개선이 필요한데, 쿼리 최적화를 하면서 튜닝하면 좋을 것 같습니다!

2024-08-19 02:46 UTC, wlgns12370 commented on src/main/java/es/princip/getp/domain/project/query/dao/ProjectApplicationQueryDslDao.java
> +    private final ProjectApplicationDao projectApplicationDao;
넵!

2024-08-19 02:47 UTC, wlgns12370 commented on src/main/java/es/princip/getp/domain/project/query/presentation/AppliedProjectQueryController.java
> +    @GetMapping("/me/applications")
좋습니다! 수정하였습니다.

2024-08-19 02:51 UTC, wlgns12370 commented on src/main/java/es/princip/getp/domain/project/query/dao/ProjectApplicationDao.java
> +    Page<AppliedProjectCardResponse> findPagedMyAppliedProjects(Pageable pageable, Long memberId, Boolean cancelled);
`AppliedProjectDao`를 추가적으로 생성하여서 처리했습니다. `ProjectDao`에 "내 프로젝트 지원 목록 조회"라는 책임까지 가지면 `SRP`가 위반된다고 생각하여서 분리하였습니다!

2024-08-19 02:53 UTC, wlgns12370 commented
@scv1702 
페어 프로그래밍으로 `Resolve` 해봅시다!

2024-08-19 05:04 UTC, scv1702 approved these changes
LGTM

2024-08-19 05:06 UTC, merged